export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_START = 'LOGIN_START';

export const FETCH_TRENDS_START = 'FETCH_TRENDS_START';
export const FETCH_TRENDS_SUCCESS = 'FETCH_TRENDS_SUCCESS';
export const FETCH_TRENDS_FAIL = 'FETCH_TRENDS_FAIL';
export const FETCH_FAIL = 'FETCH_FAIL';
