export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_START = 'LOGIN_START';

export const FETCH_TRENDS_START = 'FETCH_TRENDS_START';
export const FETCH_TRENDS_SUCCESS = 'FETCH_TRENDS_SUCCESS';
export const FETCH_TRENDS_FAIL = 'FETCH_TRENDS_FAIL';
export const FETCH_FAIL = 'FETCH_FAIL';

export const UPDATE_PAGE_VIEW_SUCCESS = 'UPDATE_PAGE_VIEW_SUCCESS';
export const UPDATE_PAGE_VIEW_FAIL = 'UPDATE_PAGE_VIEW_FAIL';

// Setting Data Types
export const SWITCH_TAB_NUMBER = 'SWITCH_TAB_NUMBER';
